//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soho_hotels.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hoteles_efEntities : DbContext
    {
        public hoteles_efEntities()
            : base("name=hoteles_efEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<act_hotel> act_hotel { get; set; }
        public virtual DbSet<actividades> actividades { get; set; }
        public virtual DbSet<cadenas> cadenas { get; set; }
        public virtual DbSet<ciudades> ciudades { get; set; }
        public virtual DbSet<hoteles> hoteles { get; set; }
    }
}
